apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.1.1"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/airflow/dags/pyspark.py
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  volumes:
    - name: dags
      hostPath:
        path: "/mnt/airflow/dags"
  driver:
    volumeMounts:
      - name: dags
        mountPath: "/opt/airflow/dags"
    cores: 1
  labels:
      version: 3.1.1
  executor:
    volumeMounts:
      - name: dags
        mountPath: "/opt/airflow/dags"
    instances: 1
    labels:
      version: 3.1.1
